### ISSUE TITLE
Users who are interns can view the shifts for their "crew"

### ISSUE THREAD

**Issue by hobson** [codeforgoodconf/free-geek#10]
Interns are volunteers that have regular, repeating shifts
Interns are members of a team of interns
Interns should be able to see their team's

**Comment by Lawlheart** [comment]
@mbrochmann We could use a Team model that has a group of Profiles

**Comment by mbrochmann** [comment]
Whoops, I did not see this mention. I'll add the issue. I assume interns can be on multiple teams?
