### ISSUE TITLE
Set up static files

### ISSUE THREAD

**Issue by Lawlheart** [codeforgoodconf/free-geek#19]

**Comment by hendricksonsarahl** [comment]
Claimed

**Comment by raehart** [comment]
I think if my effort to be able to use a static file in making the landing page look better (ticket #12)

**Comment by raehart** [comment]
I think I may have solved at least some of this.  Will submit a PR.

**Comment by hendricksonsarahl** [comment]
This appears to be functioning how Brigette implemented it, issue resolved

**Comment by raehart** [comment]
@LawlietBlack  can you go ahead and close this issue then?
