### ISSUE TITLE
Set up appointment model

### ISSUE THREAD

**Issue by raehart** [codeforgoodconf/free-geek#21]
set up a django model for appointments

**Comment by mbrochmann** [comment]
Can I try this? I will probably need help but I think I learned enough from the polls tutorial I did yesterday to do it. There will also be table and factory models which are associated with the appointments, right?

**Comment by mbrochmann** [comment]
Appointments should also have "slots", each with a "proficiency" requirement for the slot to be filled, and the "slots" should be able to be associated with a "user", or be "empty".
