### ISSUE TITLE
Set up unittest files

### ISSUE THREAD

**Issue by raehart** [codeforgoodconf/free-geek#36]
Setup unit test files and write a few basic tests to ensure tests are working.

**Comment by raehart** [comment]
Claiming

**Comment by raehart** [comment]
I'm setting up test files for models, views and forms.

**Comment by Brigette-Eckert** [comment]
In theory python manage.py test tests file name should work

**Comment by hobson** [comment]
Excellent! If someone could put that line in the `.travis.yml` file tests
should run automatically on my account every time we push. And we can put
the green/red travis badge for tests passing in our README file.

--Hobson

**Comment by raehart** [comment]
I'll work on that soon.

**Comment by raehart** [comment]
I'll open more tickets for specific tests as we need them, but the basic test files are there.  Please try to practice TDD when possible.

**Comment by mbrochmann** [comment]
Ok, I have some tests from the PR I withdrew, will add back to current PR

**Comment by mbrochmann** [comment]
Will try to get done in next few days
