### ISSUE TITLE
why doesn't styling show up with gunicorn

### ISSUE THREAD

**Issue by rachelkelly** [codeforgoodconf/free-geek#48]
it appears to not be pulling in static/.

**Comment by raehart** [comment]
If the css is inside a sub directory in static try adding {% load static from static %} to top of html file you are trying to use it from.   {% load staticfiles %} only grabs files directly in static.

**Comment by hobson** [comment]
manage.py collect static
 will help
Then need to make sure nginx is serving up the goodies in the directory that static is collected to.

Also, gunicorn and Django may not allow you to have debug=True
