### ISSUE TITLE
Fix ImportError: No module named 'django.core.context_processors' 

### ISSUE THREAD

**Issue by raehart** [codeforgoodconf/free-geek#6]
Adding to django core to requirements.txt to fix error message "ImportError: No module named 'django.core.context_processors"  when running python manage.py runserver

**Comment by Lawlheart** [comment]
this looks relevant: https://stackoverflow.com/questions/32828536/django-no-module-named-context-processors-error-after-reboot

**Comment by raehart** [comment]
We need to fix the requirements.txt to force install django 1.8 instead of django 1.11
