### ISSUE TITLE
Create Seed Data

### ISSUE THREAD

**Issue by Lawlheart** [codeforgoodconf/free-geek#87]
Until we can get some data from FG themselves, we should start making some seed data for our app.

**Comment by mbrochmann** [comment]
What form would this take? I.e. some code that populates the database? Where would it go and what would it look like?

**Comment by Lawlheart** [comment]
I'm not sure how django handles seed data, but it would basically be a file that runs a bunch of model creation. Faker is a good gem in ruby for this, to generate random names and whatnot, Python probably has something similar. I find that having some seeds really helps me visualize what I'm working with and speed up development time.

**Comment by mbrochmann** [comment]
https://semaphoreci.com/community/tutorials/generating-fake-data-for-python-unit-tests-with-faker

**Comment by Lawlheart** [comment]
I'll be handling this one
