### ISSUE TITLE
Client-side validation: user registration

### ISSUE THREAD

**Issue by hendricksonsarahl** [codeforgoodconf/free-geek#94]
## username 
When registering as a new user at `http://127.0.0.1:8000/register` if user enters a name already taken, there is no validation/error message displayed in page and instead this occurs:
**IntegrityError at /register
UNIQUE constraint failed: auth_user.username**
## password
There are some built in requirements for password strength that the Django app provides, but these requirements are not stated on the client side. When a valid password is entered, the "Submit" button becomes active. This could be improved. 
This potentially will be helpful: `https://github.com/dstufft/django-passwords`

**Comment by mbrochmann** [comment]
I'd like to tackle this, unless somebody else is already working on it. (?)

**Comment by hendricksonsarahl** [comment]
I don't believe so, go for it! Thanks Michelle!

**Comment by mbrochmann** [comment]
These issues are now fixed.

**Comment by hendricksonsarahl** [comment]
Tested, this is now resolved. Thanks Michelle!
